name: 'dq_framework'
version: '1.0.0'
config-version: 2

profile: 'snowflake_learning'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dq_framework:
    +materialized: view

vars:
  audit_database: "SNOWFLAKE_LEARNING_DB"
  audit_schema: "SCH_AUDIT"
  audit_results_table: "DQ_RESULTS"
  audit_config_table: "DQ_TABLE_CONFIG"
  audit_business_rules_table: "DQ_BUSINESS_RULES"